version: "2"
services:
  node:
    image: "node:16-slim"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:5000"  
    expose:
      - "8081"
    command: "npm start"